### ISSUE TITLE
how to get YOUR-API-KEY and IMGUR_API_KEY

### ISSUE THREAD

**Issue by lich13** [RoxasShadow/SauceNao-Windows#1]
![default](https://cloud.githubusercontent.com/assets/10644698/19010989/87d55a5c-87bd-11e6-8fa1-fe82bca9e830.PNG)
PLATFORM VERSION INFO
    Windows             : 6.1.7601.65536 (Win32NT)
    Common Language Runtime     : 4.0.30319.42000
    System.Deployment.dll       : 4.6.1081.0 built by: NETFXREL3STAGE
    clr.dll             : 4.6.1081.0 built by: NETFXREL3STAGE
    dfdll.dll           : 4.6.1081.0 built by: NETFXREL3STAGE
    dfshim.dll          : 4.0.41209.0 (Main.041209-0000)

SOURCES
    Deployment url          : file:///D:/Program%20Files/SauceNao-Windows-master/SauceNao-Windows/publish/SauceNao-Windows.application
    Application url         : file:///D:/Program%20Files/SauceNao-Windows-master/SauceNao-Windows/publish/Application%20Files/SauceNao-Windows_0_1_5_0/SauceNao-Windows.exe.manifest

IDENTITIES
    Deployment Identity     : SauceNao-Windows.application, Version=0.1.5.0, Culture=neutral, PublicKeyToken=149cffc35d72334c, processorArchitecture=msil

APPLICATION SUMMARY
    \* Installable application.

ERROR SUMMARY
    Below is a summary of the errors, details of these errors are listed later in the log.
    \* Activation of D:\Program Files\SauceNao-Windows-master\SauceNao-Windows\publish\SauceNao-Windows.application resulted in exception. Following failure messages were detected:
        + Application manifest has either a different computed hash than the one specified or no hash specified at all. 
        + File, SauceNao-Windows.exe.manifest, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
    No transaction error was detected.

WARNINGS
    There were no warnings during this operation.

OPERATION PROGRESS STATUS
    \* [2016/10/1 9:56:36] : Activation of D:\Program Files\SauceNao-Windows-master\SauceNao-Windows\publish\SauceNao-Windows.application has started.
    \* [2016/10/1 9:56:36] : Processing of deployment manifest has successfully completed.
    \* [2016/10/1 9:56:36] : Installation of the application has started.

ERROR DETAILS
    Following errors were detected during this operation.
    \* [2016/10/1 9:56:36] System.Deployment.Application.InvalidDeploymentException (HashValidation)
        - Application manifest has either a different computed hash than the one specified or no hash specified at all. 
        - Source: System.Deployment
        - Stack trace:
            at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
            at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
            at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
        --- Inner Exception ---
        System.Deployment.Application.InvalidDeploymentException (HashValidation)
        - File, SauceNao-Windows.exe.manifest, has a different computed hash than specified in manifest.
        - Source: System.Deployment
        - Stack trace:
            at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
            at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
            at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)

COMPONENT STORE TRANSACTION DETAILS
    No transaction information is available.

**Comment by lich13** [comment]
![image](https://cloud.githubusercontent.com/assets/10644698/19011082/c924f2d2-87be-11e6-8893-2858261c9453.png)

**Comment by RoxasShadow** [comment]
You can get a `SAUCENAO_API_KEY` by creating a new account and then going [here](https://saucenao.com/user.php?page=search-api).

Concerning imgur, I can't remember right now how you can get one, but I'm sure Google reminds better than me 👍
